[pytest]
markers =
    smoke: критичные проверки для CI на каждый коммит
    regression: полный набор для ночных прогонов
    os: тесты бэкенда iQuaRix OS
    b2b: тесты бэкенда iQuaRix B2B
    admin: тесты бэкенда Admin Panel

log_cli = true
log_cli_level = INFO
